import classnames from "classnames/bind";
import type { Metadata } from "next";

import HeaderDashboard from "@/components/header/HeaderDashboard";

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <HeaderDashboard />
      <h1>layout</h1>
    </main>
  );
}
